/**
 * Warp Terminal Integration
 *
 * Provides integration with Warp terminal features including:
 * - Theme configuration
 * - Workflow blocks
 * - Command history sync
 */

import type {
  Integration,
  IntegrationStatus,
  WarpConfig,
} from "./types.js";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

interface WarpTheme {
  name: string;
  background: string;
  foreground: string;
  accent: string;
  cursor: string;
}

interface WarpWorkflow {
  name: string;
  command: string;
  description?: string;
  arguments?: Array<{
    name: string;
    description?: string;
    default_value?: string;
  }>;
}

export class WarpClient implements Integration {
  private config: WarpConfig;
  private initialized = false;
  private warpConfigDir: string;

  constructor(config: WarpConfig) {
    this.config = config;
    this.warpConfigDir = path.join(os.homedir(), ".warp");
  }

  async initialize(): Promise<void> {
    // Check if Warp is installed
    const warpExists =
      fs.existsSync("/Applications/Warp.app") ||
      fs.existsSync(path.join(os.homedir(), "Applications/Warp.app")) ||
      fs.existsSync(this.warpConfigDir);

    if (!warpExists && this.config.enabled !== false) {
      // Create config directory if it doesn't exist (for non-macOS systems)
      if (!fs.existsSync(this.warpConfigDir)) {
        fs.mkdirSync(this.warpConfigDir, { recursive: true });
      }
    }

    this.initialized = true;
  }

  async getStatus(): Promise<IntegrationStatus> {
    const warpInstalled = fs.existsSync(this.warpConfigDir);
    return {
      connected: warpInstalled,
      healthy: warpInstalled,
      lastCheck: new Date(),
      metadata: {
        configDir: this.warpConfigDir,
        installed: warpInstalled,
      },
    };
  }

  async cleanup(): Promise<void> {
    this.initialized = false;
  }

  /**
   * Get Warp themes directory
   */
  private getThemesDir(): string {
    return path.join(this.warpConfigDir, "themes");
  }

  /**
   * Get Warp workflows directory
   */
  private getWorkflowsDir(): string {
    return path.join(this.warpConfigDir, "workflows");
  }

  /**
   * List installed themes
   */
  async listThemes(): Promise<string[]> {
    const themesDir = this.getThemesDir();
    if (!fs.existsSync(themesDir)) {
      return [];
    }
    return fs
      .readdirSync(themesDir)
      .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"))
      .map((f) => f.replace(/\.ya?ml$/, ""));
  }

  /**
   * Install a theme
   */
  async installTheme(theme: WarpTheme): Promise<boolean> {
    const themesDir = this.getThemesDir();
    if (!fs.existsSync(themesDir)) {
      fs.mkdirSync(themesDir, { recursive: true });
    }

    const themeContent = `
# Warp Theme: ${theme.name}
# Generated by BlackRoad OS Agents

accent: "${theme.accent}"
background: "${theme.background}"
foreground: "${theme.foreground}"
cursor: "${theme.cursor}"
terminal_colors:
  normal:
    black: "#282c34"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#e5c07b"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#abb2bf"
  bright:
    black: "#5c6370"
    red: "#e06c75"
    green: "#98c379"
    yellow: "#e5c07b"
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#ffffff"
`;

    const themePath = path.join(themesDir, `${theme.name}.yaml`);
    fs.writeFileSync(themePath, themeContent);
    return true;
  }

  /**
   * Remove a theme
   */
  async removeTheme(themeName: string): Promise<boolean> {
    const themePath = path.join(this.getThemesDir(), `${themeName}.yaml`);
    if (fs.existsSync(themePath)) {
      fs.unlinkSync(themePath);
      return true;
    }
    return false;
  }

  /**
   * List workflows
   */
  async listWorkflows(): Promise<WarpWorkflow[]> {
    const workflowsDir = this.getWorkflowsDir();
    if (!fs.existsSync(workflowsDir)) {
      return [];
    }

    const workflows: WarpWorkflow[] = [];
    const files = fs
      .readdirSync(workflowsDir)
      .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"));

    for (const file of files) {
      try {
        const content = fs.readFileSync(
          path.join(workflowsDir, file),
          "utf-8"
        );
        // Simple YAML parsing for workflow structure
        const nameMatch = content.match(/name:\s*["']?(.+?)["']?\n/);
        const commandMatch = content.match(/command:\s*["']?(.+?)["']?\n/);
        const descMatch = content.match(/description:\s*["']?(.+?)["']?\n/);

        if (nameMatch && commandMatch) {
          workflows.push({
            name: nameMatch[1],
            command: commandMatch[1],
            description: descMatch?.[1],
          });
        }
      } catch {
        // Skip invalid files
      }
    }

    return workflows;
  }

  /**
   * Create a workflow
   */
  async createWorkflow(workflow: WarpWorkflow): Promise<boolean> {
    const workflowsDir = this.getWorkflowsDir();
    if (!fs.existsSync(workflowsDir)) {
      fs.mkdirSync(workflowsDir, { recursive: true });
    }

    let content = `name: "${workflow.name}"
command: "${workflow.command}"
`;

    if (workflow.description) {
      content += `description: "${workflow.description}"\n`;
    }

    if (workflow.arguments?.length) {
      content += "arguments:\n";
      for (const arg of workflow.arguments) {
        content += `  - name: "${arg.name}"\n`;
        if (arg.description) {
          content += `    description: "${arg.description}"\n`;
        }
        if (arg.default_value) {
          content += `    default_value: "${arg.default_value}"\n`;
        }
      }
    }

    const workflowPath = path.join(
      workflowsDir,
      `${workflow.name.replace(/\s+/g, "-").toLowerCase()}.yaml`
    );
    fs.writeFileSync(workflowPath, content);
    return true;
  }

  /**
   * Remove a workflow
   */
  async removeWorkflow(workflowName: string): Promise<boolean> {
    const workflowPath = path.join(
      this.getWorkflowsDir(),
      `${workflowName.replace(/\s+/g, "-").toLowerCase()}.yaml`
    );
    if (fs.existsSync(workflowPath)) {
      fs.unlinkSync(workflowPath);
      return true;
    }
    return false;
  }

  /**
   * Create BlackRoad theme
   */
  async installBlackRoadTheme(): Promise<boolean> {
    return this.installTheme({
      name: "blackroad",
      background: "#0d1117",
      foreground: "#c9d1d9",
      accent: "#58a6ff",
      cursor: "#58a6ff",
    });
  }

  /**
   * Create BlackRoad workflows
   */
  async installBlackRoadWorkflows(): Promise<boolean> {
    const workflows: WarpWorkflow[] = [
      {
        name: "BlackRoad Deploy",
        command: "br-agent deploy {{service}}",
        description: "Deploy a BlackRoad service",
        arguments: [
          {
            name: "service",
            description: "Service name to deploy",
          },
        ],
      },
      {
        name: "BlackRoad Status",
        command: "br-agent status",
        description: "Check BlackRoad agent status",
      },
      {
        name: "BlackRoad Logs",
        command: "br-agent logs {{service}} --tail {{lines}}",
        description: "View BlackRoad service logs",
        arguments: [
          {
            name: "service",
            description: "Service name",
          },
          {
            name: "lines",
            description: "Number of lines",
            default_value: "100",
          },
        ],
      },
    ];

    for (const workflow of workflows) {
      await this.createWorkflow(workflow);
    }

    return true;
  }
}
